version: '3.3'
services:
  my_db:
    image: mysql:8.3.0-oracle
    container_name: rest_webservices-mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'social-media'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '${MYSQL_PORT}:3306'  # <Port exposed> : <port running inside container>
    volumes:
      - .mysql_java-rest:/var/lib/mysql   # Where our data will be persisted
    networks:
      - rest_mysql
  java:
    image: stefanbk/rest_webservices-docker
    container_name: rest_webservices-java_springboot
    restart: always
    ports:
      - '${JAVA_SPRINGBOOT_PORT}:8081' # <Port exposed> : <port running inside container>
    networks:
      - rest_mysql
networks:
  rest_mysql:
    driver: bridge
# Names our volume
volumes:
  .mysql_java-rest: